### ISSUE TITLE
GitHub discussions closed in favor of discord

### ISSUE THREAD

**Issue by Trey2k** [WeaselGames/godot_luaAPI#121]
I have closed the GitHub discussions page on this project in favor of our [Discord](https://discord.gg/vGazqdQZ7p) or [Matrix](https://matrix.weaselgames.net/#/room/#weaselgames:weaselgames.net).

**Comment by michieal** [comment]
> Kinda disappointing that people are moving away from more public discussion areas into these walled garden information black holes.

The only difference between here and your "walled garden information black holes" is that the latter is not google searchable. But, on the positive side, you don't have to wait for a web page to notify you that the person that you are talking to has responded. Discord is an instant messenger, whereas github issues is a bulletin board. Personally, I'd rather just use the instant messenger format and be able to have a discussion than a hit or miss bulletin board system like Github's Issues. (Or if you prefer, an outdated forum style, where you write a letter and wait for the other person to read it, and mail you back a letter. I'm more of a telephone guy than an electronic snail mail guy.)
But, that's just my opinion... Tech is supposed to make life quicker, easier and with better access to the internet... *not* keep us in 1986 using BBSes.

**Comment by Trey2k** [comment]
> Kinda disappointing that people are moving away from more public discussion areas into these walled garden information black holes.

I understand that it would be nice if Q&A was indexable by search engines and or just had a better method of search then what Discord provides.

GitHub Discussions was not closed to intentionally wall off information. The reason it was closed is it was not utilized, we would get 1 post every 4 or 5 months which would take awhile to get a response since not many people monitor it. Where as the Discord is fairly active. So it was closed to at least consolidate where information is.

This is tagged as wontfix but if there is enough drive behind it, discussions can be re-opened.

**Comment by michieal** [comment]
From experience, I will say this: 
* it's not the "blenert" sound, as that's annoying. It's that communication works better if you can "talk" rather than "mail" each other.
* Forum style information areas do not reduce duplicate questions. People do not go through and search before asking. (Not that they don't quickly google search things.) But, a lot of things that I have personally searched for on, say, stackoverflow have had a high rate of "duplicate question" tags. And, having had to be one of the people answering issue tickets for an active OSS issue tracker I can definitely say that there's a reason that it has "Duplicate Question" label; one guy made 45 different duplicate questions in one day. 

Also on the whole forum style communication for getting answers, things get lost. I've seen unanswered questions linger there for *years* unanswered. And, that is generally not the case with an Instant Message style communication format.

I do believe that there is a discord IRC bridge, and I know that there is a discord matrix bridge. They both require someone to maintain them, and maintain the associated services. In usage, I have seen people get confused by the `BOT` tag after the person's name that is on the opposite side of the bridge, and have had people tell real users to "get lost bot." Most people looking for answers are put off by being dismissed, and I think rightfully so. So, there is that. 

If it helps any, there are open source discord clients.

**Comment by Trey2k** [comment]
Okay, I am still finding out how matrix works. But I have a server setup now with the discord bridge. There is a room which should have all discord channels by default. Here is the invite link https://matrix.weaselgames.net/#/room/#weaselgames:weaselgames.net

@JasonTable I hope this can work for you. Let me know

**Comment by Trey2k** [comment]
> well i think this is a good step in the right direction. but i dont think it works for me. i tried joining the matrix space with my account and none of the rooms are showing up. just an empty space with 5 members.

Yes sadly this is a issue I noticed as well. If you manually add each room it should still allow you to join. I have been talking in with the dendrite guys and apparently [this](https://github.com/matrix-org/dendrite/issues/2504#issuecomment-1175913274) is the issue we are facing. 

The issue seems to only happen with federated accounts. For some reason if the account uses the weaselgames homeserver there is no issue. 

Here is each room address:
- #general:weaselgames.net
- #luaapi:weaselgames.net
- #godot:weaselgames.net
- #off-topic:weaselgames.net

**Comment by Trey2k** [comment]
I am considering doing a full reset and moving over to synapse. Dendrite is cool, but seems to be very unstable and is missing many moderation features. We will see though, maybe the issue can be fixed soon.

**Comment by Trey2k** [comment]
> well i think this is a good step in the right direction. but i dont think it works for me. i tried joining the matrix space with my account and none of the rooms are showing up. just an empty space with 5 members.

This issue should be resolved now actually
